---
title: jekyll-test
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  tutorial:
    title: Tutorial
    output: true
  uploads:
    title: Uploads
    output: true
subtitle: Painless documentation for your projects
disqus_shortname: 
google_analytics_id: 
navigation: 2
codeurl: https://github.com/rallech/jekyll_test
sections:
- - doc
  - Documentation
- - tut
  - Tutorial
- - ref
  - Reference
- - dev
  - Developers
- - post
  - Posts
baseurl: 
permalink: none
highlighter: rouge
future: true
exclude:
- bin
- README.md
markdown: kramdown
redcarpet:
  extensions:
  - no_intra_emphasis
  - fenced_code_blocks
  - autolink
  - strikethrough
  - superscript
  - with_toc_data
  - tables
  - hardwrap
